# Generated by Django 5.1.4 on 2024-12-18 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0002_feature_model_product_model_complaints_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_model',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints_model',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
