# Generated by Django 5.1.4 on 2024-12-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0004_feedback_model_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_model',
            name='created_at',
            field=models.DateField(auto_now_add=True, default="2024-12-03"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback_model',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
