# Generated by Django 5.1.4 on 2024-12-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0006_remove_feedback_model_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_model',
            name='LOGIN_ID',
        ),
        migrations.AddField(
            model_name='feedback_model',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growapp.user_model'),
        ),
    ]
