# Generated by Django 5.1.4 on 2024-12-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0007_remove_feedback_model_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growapp.login_model'),
        ),
    ]
