# Generated by Django 5.1.4 on 2024-12-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0008_product_model_details_alter_feedback_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_model',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growapp.user_model'),
        ),
    ]
