# Generated by Django 5.1.4 on 2024-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growapp', '0011_alter_feedback_model_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='manageseeds_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seed_image', models.FileField(blank=True, null=True, upload_to='seeds/')),
                ('Tempurature', models.CharField(blank=True, max_length=100, null=True)),
                ('Humidity', models.CharField(blank=True, max_length=100, null=True)),
                ('Moisture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
